### PR TITLE
MGDOBR-669 Removing authentication from Error Catalog API

### PR DESCRIPTION
**Pull request by vpellegrino**
[MGDOBR-669](https://issues.redhat.com/browse/MGDOBR-669)

In order to implement MGDOBR-669 we are removing authentication from `/error/*` endpoints like has been done in Kafka and Service Registry (you can refer to https://github.com/redhat-developer/app-services-sdk-js/blob/main/scripts/errors/fetch-errors.sh)

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [ ] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [ ] The layers in the `kustomize` folder have been updated accordingly.
- [ ] All new functionality is tested
- [ ] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.
- <b>Deploy BOT</b>
  Comment with `/deploy <dev,stable> when the PR has been merged to deploy to a target environment.

</details>

### CODE REVIEW

**Review by manstis — CHANGES_REQUESTED** [review]
LGTM. You'll need to build `manager` locally and copy `manager\target\generated\openapi.yaml` to `openapi` though.

**Review by manstis — APPROVED** [review]
Thank-you.

**Review by r00ta — APPROVED** [review]

**Comment by r00ta** [comment]
I will merge as soon as CI is green

**Comment by vpellegrino** [comment]
It seems we have two IT fails:
1) `[ERROR] Slack Action tests - Slack Action Processor is created and slack message should be received in the slack channel  Time elapsed: 55.658 s  <<< ERROR!`
2) `[ERROR] Slack Source tests - Slack Source Processor is created and slack message as source should result into other generated slack message  Time elapsed: 0.829 s  <<< ERROR!`
I am not sure they are related to this PR.
Could someone confirm? Please let me know if any action is required from my side.

**Comment by manstis** [comment]
@vpellegrino The "Managed Connector" environment we use (for Actions on Processors) is broken.

All PRs in `sandbox` are failing at this moment for the same reason. Team members are aware.

**Review by danielezonca — APPROVED** [review]

**Comment by danielezonca** [comment]
Yes, the failure is unrelated and we can probably merge, this PR is safe

**Pull request merged**
