### PR TITLE
MGDOBR-1207: Move versioned Maven Artifacts to parent-child modules

### PR DESCRIPTION
**Pull request by manstis**
[https://issues.redhat.com/browse/MGDOBR-1207](https://issues.redhat.com/browse/MGDOBR-1207)

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [x] The layers in the `kustomize` folder have been updated accordingly.
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.
- <b>Deploy BOT</b>
  Comment with `/deploy <dev,stable> when the PR has been merged to deploy to a target environment.

</details>

### CODE REVIEW

**Comment by manstis** [comment]
@sutaakar @jiripetrlik Do you know if my failures are "chicken and egg"?

This PR includes a change to the GHA workflow due to code re-organisation in the PR too.. however when the PR is created the old GHA workflow is presumably used? I cannot merge the GHA workflow change in a separate PR since at that point in time the code remains laid out the old way...

**Review by r00ta — APPROVED** [review]

**Comment by r00ta** [comment]
@msmagnanijr is there anything we need to change on app-interface side? We are moving `manager/pom.xml` to `/manager-parent/manager/pom.xml` with this PR, I can't find on app-interface if we set this path to build the downstream images

**Comment by sutaakar** [comment]
@manstis GHA changes from PR are not reflected. You can use 3 branches approach to test this:
1. Push a branch containing all your changes into dedicated branch on upstream repo.
2. Push a second branch on top of the previous branch into upstream repo changing i.e. https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/blob/main/.github/workflows/Manager-CI.yaml#L6 to your second branch
3. open a sample PR targeting second branch which triggers needed checks

**Comment by msmagnanijr** [comment]
> @msmagnanijr is there anything we need to change on app-interface side? We are moving `manager/pom.xml` to `/manager-parent/manager/pom.xml` with this PR, I can't find on app-interface if we set this path to build the downstream images
 
hey @r00ta I do not think so. To build the images we use this [script](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/blob/main/app-interface/app_sre_fleet_manager_build_push.sh)  and in app-interface I also don't see a direct reference to that dir: https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/rhose/cicd/saas/rhose.yml

so I think it's ok.

**Comment by manstis** [comment]
`Bridge`, `Manager` and `Update` CI builds are [here](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/1285).

They do not work on this PR since the revised GHA definitions are not used for this PR itself.

**Review by sutaakar — APPROVED** [review]

**Comment by r00ta** [comment]
merged as it was properly tested here https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/1285

**Pull request merged**
