### PR TITLE
MGDOBR-458 Extend Bridge creation timeout in integration tests

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

[MGDOBR-458](https://issues.redhat.com/browse/MGDOBR-458)

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

### CODE REVIEW

**Review by Srihari1192 — APPROVED** [review]

**Comment by manstis** [comment]
Please be aware of https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/480

At the moment when a Bridge/Processor is requested we trigger work to provision it immediately.

After the referenced PR is merged provisioning will not start immediately but on the first poll of a "work queue".

Polling is every 30s at 0s and 30s on the minute.

I see you've doubled the time-out so you _may not_ be affected.. just FYI.

**Comment by sutaakar** [comment]
`Timeout reached while creating topic and granting access to topic`
Rerunning the tests, hopefully it was just a short term outage

**Review by jiripetrlik — COMMENTED** [review]
Looks good to me. Maybe can we set some default value somewhere? Is it possible to for example use:
`the Bridge "mybridge" is existing with status "ready"` - and use the default timeout 
and use `within 4 minutes` only in some special case where longer timeout is needed?

**Comment by sutaakar** [comment]
@jiripetrlik I rather prefer current solution with declared timeout, that makes the step explicit and without hidden functionality/configuration.

**Comment by radtriste** [comment]
@jiripetrlik I do agree with @sutaakar. Steps to be as explicit as possible on what is happening.

**Review by radtriste — APPROVED** [review]

**Pull request merged**
