### PR TITLE
Move to bash shell

### PR DESCRIPTION
**Pull request by manstis**
No JIRA.

I had to run the existing scripts with `bash ...` on Ubuntu.

`source` is only available in `bash` and not `sh`.

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [ ] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [ ] All new functionality is tested
- [ ] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

### CODE REVIEW

**Comment by kostola** [comment]
What is the purpose of this change?

**Comment by manstis** [comment]
@kostola so the scripts I was recommended to use work on Ubuntu that uses `bash`.

`sh` does not understand `source` (in the scripts) on Ubuntu.

**Comment by lucamolteni** [comment]
> @kostola so the scripts I was recommended to use work on Ubuntu that uses `bash`.
> 
> `sh` does not understand `source` (in the scripts) on Ubuntu.

are you sure about this? bash should be a superset of sh.

Anyway we can't assume bash is installed for example in macOS

**Comment by manstis** [comment]
> I think this can be closed

If we can come up with another solution for people for which `source` is available (or the use is re-worked) I agree.

https://stackoverflow.com/questions/13702425/source-command-not-found-in-sh-shell

**Comment by manstis** [comment]
OK, I see @lucamolteni work around now.. this can be closed.

**Comment by manstis** [comment]
Replaced by https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/514

**Pull request closed without merging**
