### PR TITLE
[NO-JIRA] - Update Template to add RDS secret reference

### PR DESCRIPTION
**Pull request by msmagnanijr**
Signed-off-by: Mauricio Magnani <msmagnanijr@gmail.com>

[Insert JIRA Issue number and update link](https://issues.redhat.com/browse/MGDOBR-)

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [ ] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [ ] All new functionality is tested
- [ ] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

### CODE REVIEW

**Comment by msmagnanijr** [comment]
```
oc process -f  app-interface/manifests/rhose-fleet-manager.yml --local -p FLEET_MANAGER_IMAGE="quay.io/app-sre/rhose-fleet-manager"  | oc apply --dry-run --validate -f -
W0405 15:14:27.613893  295423 helpers.go:555] --dry-run is deprecated and can be replaced with --dry-run=client.
W0405 15:14:27.616167  295422 shim_kubectl.go:55] Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to "template.openshift.io/v1" for your resource
deployment.apps/rhose-fleet-manager created (dry run)
service/rhose-fleet-manager created (dry run)
```

**Comment by msmagnanijr** [comment]
I also removed some params that were not needed.

**Comment by r00ta** [comment]
pipelines should not run for `app-interface` files, see https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/580

**Comment by msmagnanijr** [comment]
> I'm wondering if it is possible to configure app-interface to fetch stuff from a different upstream branch like `app-interface-test` so that you can make all the tests you want without PR approvals. And once we are happy, we can raise a PR on main. It would save you a lot of time I guess

That makes sense! I believe it is possible but first, let me see what this might impact my current configs.

**Review by danielezonca — APPROVED** [review]

**Pull request merged**
