### PR TITLE
MGDOBR-332 - Continuous Testing of our Stable Environment

### PR DESCRIPTION
**Pull request by jiripetrlik**
[MGDOBR-332](https://issues.redhat.com/browse/MGDOBR-332)

The stable environment should be continuously tested using our E2E tests.

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [*] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [*] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [*] All new functionality is tested
- [*] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [*] Pull Request contains link to the JIRA issue
- [*] Pull Request contains link to any dependent or related Pull Request
- [*] Pull Request contains description of the issue
- [*] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [*] Check if code and Github action workflows have been modified and if the modification is safe
- [*] If the modification is safe, add the `safe to test` label

### CODE REVIEW

**Comment by robpblake** [comment]
@jiripetrlik What do we need to do in order to get this merged?

cheers,

Rob

**Comment by robpblake** [comment]
@jiripetrlik What do we need to do in order to get this merged?

cheers,

Rob

**Comment by jiripetrlik** [comment]
Hello @robpblake ,
I've refreshed the original PR. It should be ready. The only thing we need to do is to create following secrets for stable cluster:
- STABLE_CLUSTER_MANAGER_URL
- STABLE_CLUSTER_KEY_CLOAK_URL
- STABLE_CLUSTER_BRIDGE_TOKEN_USERNAME
- STABLE_CLUSTER_BRIDGE_TOKEN_PASSWORD

**Review by robpblake — APPROVED** [review]
Thanks @jiripetrlik . Can you please send an email to the team letting them know that this is now available once this is merged.

cheers,

Rob

**Review by sutaakar — APPROVED** [review]

**Pull request merged**
