### PR TITLE
MGDOBR-446: Processor with Failed dependencies is not marked as Failed

### PR DESCRIPTION
**Pull request by manstis**
[https://issues.redhat.com/browse/MGDOBR-446](https://issues.redhat.com/browse/MGDOBR-446)

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

### CODE REVIEW

**Comment by manstis** [comment]
@lucamolteni @kostola I tested this locally by setting the following.
```
MANAGED_CONNECTORS_CLUSTER_ID=bananna
OPENSHIFT_OFFLINE_TOKEN=bannna
```
I watched successive failed attempts to provision a Managed Connector before the Processor was set as {{FAILED}}.
```
{
  "kind": "ProcessorList",
  "items": [
    {
      "kind": "Processor",
...
      "status": "failed",
      "action": {
        "type": "Slack",
        "parameters": {
          "channel": "...",
          "webhookUrl": "..."
        }
      }
    }
  ]
}
```

**Comment by manstis** [comment]
@sutaakar I added you as QE (as you have OB experience) however you may like to introduce @jomarko to things?

**Comment by lucamolteni** [comment]
Getting a consistent

```

[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ProcessorAPITest.testDeleteProcessor:324 1 expectation failed.
Expected status code <202> but was <500>.

[ERROR] Errors:
[ERROR]   ProcessorServiceTest.testUpdateProcessorStatusReadyPublishedAt:246 » ArcUndeclaredThrowable
[INFO]
[ERROR] Tests run: 183, Failures: 1, Errors: 1, Skipped: 0



``` 

While running `mvn clean test` from the manager directory. We should fix this before merging

**Comment by lucamolteni** [comment]
Getting a consistent

```

[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ProcessorAPITest.testDeleteProcessor:324 1 expectation failed.
Expected status code <202> but was <500>.

[ERROR] Errors:
[ERROR]   ProcessorServiceTest.testUpdateProcessorStatusReadyPublishedAt:246 » ArcUndeclaredThrowable
[INFO]
[ERROR] Tests run: 183, Failures: 1, Errors: 1, Skipped: 0



``` 

While running `mvn clean test` from the manager directory. We should fix this before merging

**Review by robpblake — APPROVED** [review]
Code changes are OK from me. I'll approve pending investigation into the test failures reported by @lucamolteni .

cheers,
Rob

**Comment by manstis** [comment]
Re-running locally again and again and again.... still no failures (for me).

**Comment by manstis** [comment]
@lucamolteni Green here too (sort of good, sort of bad).

**Review by sutaakar — APPROVED** [review]

**Comment by lucamolteni** [comment]
> @lucamolteni Green here too (sort of good, sort of bad).

Doesn't fail anymore after the rebase

**Review by lucamolteni — APPROVED** [review]

**Pull request merged**
