### PR TITLE
MGDOBR-206 Create CI pipeline to execute E2E BDD tests

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

[MGDOBR-206](https://issues.redhat.com/browse/MGDOBR-206) 

The pipeline builds complete repository, deploys all images into KinD, installs environment using kustomize and executes integration tests against deployed environment.
Fixed minor issue in operator revealed by tests.

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by jiripetrlik — APPROVED** [review]
Looks good to me.

**Comment by sutaakar** [comment]
There is currently one test failure related to metrics - metric related to deleted processes/bridges has more counts than expected. I suspect that operator sends delete status updates several times (need to be confirmed). Question is how to address the issue.

**Review by r00ta — APPROVED** [review]

**Comment by r00ta** [comment]
@sutaakar see https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/283

**Comment by sutaakar** [comment]
@r00ta FYI I have adjusted processor metric to update after processor is deleted from database to prevent wrong metric values in case Processor fails to be deleted from database (i.e. OptimisticLockException).

**Pull request merged**
