### PR TITLE
MGDOBR-499: Fix wrong assertj calls order

### PR DESCRIPTION
**Pull request by jomarko**
[MGDOBR-499](https://issues.redhat.com/browse/MGDOBR-499)

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [ ] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [ ] All new functionality is tested
- [ ] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko This ITs fail.. https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/runs/5751160413?check_suite_focus=true This is why I'm trying to run them locally to figure out what the problem is... there are lots of PRs failing on IT atm.

**Comment by jomarko** [comment]
@manstis I am checking the test locally, will let you know if I have some findings

**Review by Srihari1192 — APPROVED** [review]

**Review by manstis — APPROVED** [review]

**Comment by manstis** [comment]
Oh, I removed and re-added the label as I was expecting more than 2 checks to be ran.. 

It seems like GHA only wants two!?

**Comment by manstis** [comment]
GHA isn't even running a build for the `infra` module containing the changed files... that is unexpected!

**Comment by manstis** [comment]
Unless "CI / Build all images and run E2E tests..." now includes it.. I'm sure we used to have ~7 checks.

**Pull request closed without merging**
