### PR TITLE
MGDOBR-233: deploy 2 manager replicas

### PR DESCRIPTION
**Pull request by r00ta**
[MGDOBR-233](https://issues.redhat.com/browse/MGDOBR-233) 

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

* <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

* <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

### CODE REVIEW

**Comment by robpblake** [comment]
Thanks @r00ta . I think lets hold this one until we've got #402 merged. I think adding in multiple replicas of Fleet Manager at the same time as #402  is probably going to cause us too many changes in one go.

cheers,

Rob

**Review by kostola — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]

**Comment by r00ta** [comment]
@robpblake are we good to go?

**Comment by r00ta** [comment]
> @robpblake are we good to go?

@robpblake ping

**Comment by robpblake** [comment]
@r00ta Not yet. The environment is still being stabilised. I don't want to add more changes until we're comfortable things are working.

cheers,
Rob

**Pull request merged**
