### PR TITLE
MGDOBR-976: include tls certificates in BridgeDTO

### PR DESCRIPTION
**Pull request by r00ta**
[MGDOBR-976](https://issues.redhat.com/browse/MGDOBR-976)

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [ ] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [ ] The layers in the `kustomize` folder have been updated accordingly.
- [ ] All new functionality is tested
- [ ] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.
- <b>Deploy BOT</b>
  Comment with `/deploy <dev,stable> when the PR has been merged to deploy to a target environment.

</details>

### CODE REVIEW

**Review by manstis — APPROVED** [review]
LGTM... but I have to ask; is there any benefit having `TlsCertificateProvider` vs injecting the `@ConfigProperty`'s directly?

**Comment by r00ta** [comment]
> LGTM...
> 
> but I have to ask; what is the benefit having `TlsCertificateProvider` vs injecting the `@ConfigProperty`'s into `BridgeService`?

Yeah.. it was my personal bias. I've removed it now

**Comment by r00ta** [comment]
@msmagnanijr we have to add `EVENT_BRIDGE_DNS_SUBDOMAIN_TLS_CERTIFICATE` and `EVENT_BRIDGE_DNS_SUBDOMAIN_TLS_KEY` for the app-sre manager

**Review by jiripetrlik — APPROVED** [review]
Looks good to me.

**Comment by msmagnanijr** [comment]
> @msmagnanijr we have to add `EVENT_BRIDGE_DNS_SUBDOMAIN_TLS_CERTIFICATE` and `EVENT_BRIDGE_DNS_SUBDOMAIN_TLS_KEY` for the app-sre manager

great! tks :)

**Pull request merged**
