### PR TITLE
MGDOBR-1293 Upgrade Jaeger operator version to v1.39.0-3

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

[MGDOBR-1293](https://issues.redhat.com/browse/MGDOBR-1293)

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-XXX] - $clear_explanation_of_what_you_did"
- [x] The layers in the `kustomize` folder have been updated accordingly.
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.
- <b>Deploy BOT</b>
  Comment with `/deploy <dev,stable> when the PR has been merged to deploy to a target environment.

</details>

### CODE REVIEW

**Review by winklerm — APPROVED** [review]

**Comment by robpblake** [comment]
@sutaakar Should we update all existing environments to use this version of Jaegar as well?

**Comment by sutaakar** [comment]
@robpblake It (hopefully) shouldn't affect any functionality we use so why not.

**Comment by robpblake** [comment]
> @robpblake It (hopefully) shouldn't affect any functionality we use so why not.

Well...considering we would use these scripts in the event of needing to rebuild our `prod` data plane, I think we should test that everything works :-)

Is the rebuilt `stage` environment the only place we can test this?

cheers,

Rob

**Comment by sutaakar** [comment]
@robpblake We can test this also in perf cluster automation. I have tried it there and operator got successfully installed. Though I didn't check whether it affects the RHOSE operator itself as we aren't able to provision it yet on perf cluster.

**Comment by sutaakar** [comment]
@robpblake The dev cluster is running the Jaeger 1.39.0-3 too, tests are passing.

**Review by msmagnanijr — APPROVED** [review]

**Pull request merged**
