### PR TITLE
MGDOBR-72: add liveness and readiness probe checks to ingress and executor deployments

### PR DESCRIPTION
**Pull request by r00ta**
[MGDOBR-72](https://issues.redhat.com/browse/MGDOBR-72) 

This PR aims to add the liveness and readiness probe checks to the ingress and executor deployements.

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Comment by sutaakar** [comment]
Looks like integration tests will need to use real images instead of mocks (and install Kafka into KinD).

**Comment by robpblake** [comment]
> Looks like integration tests will need to use real images instead of mocks (and install Kafka into KinD).

**Comment by robpblake** [comment]
@r00ta Apologies, accidentally closed this PR.

**Comment by robpblake** [comment]
@sutaakar Alternatively, just mount a `ConfigMap` containing dummy HTML onto the docroot on the nginx container at `/q/health/live` and `/q/health/ready`

**Comment by robpblake** [comment]
@r00ta Does this cause the pods to `CrashLoopBackOff` if the internal Kafka is unavailable?

**Comment by r00ta** [comment]
> Looks like integration tests will need to use real images instead of mocks (and install Kafka into KinD).

Yeah.. with the new liveness/readiness probes we expect some endpoints to be available (`/q/health/live` and `/q/health/ready`), and `nginx` image we are using now does not expose them. 
For this tests we could also create an empty quarkus application that exposes those endpoints, push it to quay and use them in the tests. wdyt @sutaakar ?

**Comment by r00ta** [comment]
> @r00ta Does this cause the pods to `CrashLoopBackOff` if the internal Kafka is unavailable?

If kafka is not available the readiness/liveness checks will fail and kubernetes will keep trying to re-deploy the pod

**Comment by sutaakar** [comment]
@r00ta Yes, that may be better option as Kafka is quite resource heavy.

**Comment by robpblake** [comment]
@sutaakar / @r00ta If we can avoid creating another app to maintain, that would be 👍 

So what I'm thinking here is `ConfigMap` with HTML in it:

```
apiVersion: v1
data:
  index: |-
    <html>
    <body>
    <h1>I'm Alive</h1>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: html-for-liveness-and-readiness
```

And then just mount ^ onto the pod for Nginx at the correct location e.g. if `docroot` is `/var/www/nginx`:

```
spec:
  containers:
    - image: nginx
      ...
      volumeMounts:
        - mountPath: /var/www/nginx/q/health/live/index.html
          name: index
        - mountPath: /var/www/nginx/q/health/ready/index.html
         name: index
  volumes:
    - configMap:
        defaultMode: 420
        name: html-for-liveness-and-readiness
      name: index
```

**Comment by sutaakar** [comment]
Well, the Deployment is completely managed by operator. So currently we can do such workaround, though it may become unusable when/if operator will monitor resources for changes.

**Comment by r00ta** [comment]
@sutaakar @robpblake I've created an empty quarkus application with the health addon enabled and pushed it here https://quay.io/repository/jrota/openbridge-empty-it-image?tab=info . If you are ok with this approach, I can create this repo under our quay organization and push it here. I don't think we need to push the code somewhere, because It's just the quarkus getting-started + the heath addon

**Comment by r00ta** [comment]
Tests are green with ^^ image

**Comment by sutaakar** [comment]
fine for me

**Comment by robpblake** [comment]
Works for me @r00ta . Thanks !

**Review by sutaakar — APPROVED** [review]

**Review by robpblake — APPROVED** [review]

**Pull request merged**
