### PR TITLE
MGDOBR-183: add https to ingress application

### PR DESCRIPTION
**Pull request by r00ta**
[MGDOBR-183](https://issues.redhat.com/browse/MGDOBR-183) 

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by robpblake — APPROVED** [review]
LGTM @r00ta 

Can you add an issue to our backlog to put in place an integration test to verify that we're enforcing the HTTP --> HTTPS redirect on the Ingress. I don't think we can do this until we're running our tests against a deployment on Openshift, which hopefully we're not too far from doing.

**Comment by robpblake** [comment]
@r00ta Alternatively it does look like we can use `mkcert` in combination with minikube to give us SSL ingress locally as well: https://minikube.sigs.k8s.io/docs/tutorials/custom_cert_ingress/

**Review by danielezonca — APPROVED** [review]

**Comment by r00ta** [comment]
> @r00ta Alternatively it does look like we can use `mkcert` in combination with minikube to give us SSL ingress locally as well: https://minikube.sigs.k8s.io/docs/tutorials/custom_cert_ingress/, but we'd need to check if the default Ingress implementation that comes with Minikube allows for enforcement of the HTTP --> HTTPS redirect

@robpblake Do we have to setup https also for minikube? Our k8s support is intended to be just for development. Even if we setup that for k8s, the ocp side would not be "tested". The only way to test this thing is to run an IT/E2E test against the platform deployed on ocp. 
I think we can avoid setting this up for k8s, but if you have a different opinion let's discuss.

**Review by kostola — APPROVED** [review]

**Comment by robpblake** [comment]
> > @r00ta Alternatively it does look like we can use `mkcert` in combination with minikube to give us SSL ingress locally as well: https://minikube.sigs.k8s.io/docs/tutorials/custom_cert_ingress/, but we'd need to check if the default Ingress implementation that comes with Minikube allows for enforcement of the HTTP --> HTTPS redirect
> 
> @robpblake Do we have to setup https also for minikube? Our k8s support is intended to be just for development. Even if we setup that for k8s, the ocp side would not be "tested". The only way to test this thing is to run an IT/E2E test against the platform deployed on ocp. I think we can avoid setting this up for k8s, but if you have a different opinion let's discuss.

@r00ta The reason I was thinking about it is that it would help us avoid a test suite that has to understand if it's running against MiniKube or OSD e.g. "The suite is running against MiniKube, do not test the SSL redirect" and also further remove any differences between local dev and production.

I don't want to hold up this PR, so I'm happy for us to add a task to our backlog to decide how we want to proceed with testing the SSL redirect (and if we want to enable SSL on the local dev experience)

cc @sutaakar for awareness of the question on testing

**Comment by r00ta** [comment]
> > > @r00ta Alternatively it does look like we can use `mkcert` in combination with minikube to give us SSL ingress locally as well: https://minikube.sigs.k8s.io/docs/tutorials/custom_cert_ingress/, but we'd need to check if the default Ingress implementation that comes with Minikube allows for enforcement of the HTTP --> HTTPS redirect
> > 
> > 
> > @robpblake Do we have to setup https also for minikube? Our k8s support is intended to be just for development. Even if we setup that for k8s, the ocp side would not be "tested". The only way to test this thing is to run an IT/E2E test against the platform deployed on ocp. I think we can avoid setting this up for k8s, but if you have a different opinion let's discuss.
> 
> @r00ta The reason I was thinking about it is that it would help us avoid a test suite that has to understand if it's running against MiniKube or OSD e.g. "The suite is running against MiniKube, do not test the SSL redirect" and also further remove any differences between local dev and production.
> 
> I don't want to hold up this PR, so I'm happy for us to add a task to our backlog to decide how we want to proceed with testing the SSL redirect (and if we want to enable SSL on the local dev experience)
> 
> cc @sutaakar for awareness of the question on testing

https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/220#issuecomment-1015247184

**Pull request merged**
