### PR TITLE
[Experiment]  Exploration of asynchronous processing for discussions

### PR DESCRIPTION
**Pull request by robpblake**
This PR is a draft. It is a strawman  to help us converge on a solution for our asynchronous workload processing. 

In this PR I expose the concepts that I've mentioned on #369 as comments. So in this PR I

- Extend the ideas of workers put forward by @lucamolteni and @r00ta 
- Extend our Entities to be the source of truth as to their status. 
- Workers inspect the environment to determine if they have done all the work to deploy dependencies. They are designed to be idempotent
- Made clear the idea of a work queue and allowed the implementation to be pluggable. I've provided an incredibly basic implementation of a work queue using the DB

**NOTE** The tests will fail. This is purely to aid discussion.

Please make sure that your PR meets the following requirements:

- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [ ] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [ ] All new functionality is tested
- [ ] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

* <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

* <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

### CODE REVIEW

**Comment by robpblake** [comment]
@r00ta @lucamolteni @manstis I've used today to dive back into our code. I've created this PR to help explain  my thoughts on how we can do asynchronous processing. It's there to help with our discussions on Monday and give you all concrete examples to look at.

Please add comments, queries or point out what I've missed.

cheers,

Rob

**Comment by manstis** [comment]
Cool. 

After a quick scan I have some thoughts on your proposal already. I'll endeavour to put them into writing once I've reviewed it in an IDE.

**Comment by robpblake** [comment]
> Cool.
> 
> After a quick scan I have some thoughts on your proposal already. I'll endeavour to put them into writing once I've reviewed it in an IDE.

Thanks @manstis . Just to reiterate in-case you missed the description. The tests definitely DO NOT pass, and I'm not even 100% sure it compiles. I wanted to get a bare-bones example for you all to look at, rather than me hand-waving and explaining things on Monday.

cheers,

Rob

**Comment by manstis** [comment]
Whilst there is nothing particularly wrong with your approach @robpblake I'd personally prefer a greater separation of concerns for the individual state changes. I think your approach could become unwieldy if for example we ended up with something (in the future) having a chain of many interdependent dependencies; for example: A needs B that needs C that needs D; i.e. create D, then C, then B and finally A (we have this for Connector->Processor already). IMO your code for Bridge is nice, Processor less nice and Connector a bit messy.

I prefer a decoupled approach such as:
- class `Event1StateHandler` handles state changes from S1 (current state) to S2 (desired state).
- class `Event2StateHandler` handles state changes from S2 (current state) to S3 (desired state).
etc

We start the transition by firing creating the Worker with current state S1 and desired state S2; then fire Event1. This is consumed by `Event1StateHandler` making changes to move state from S1 to S2. When successful class `Event1StateHandler` updates the current state to S2 and desired state to S3; then fires Event2. This in turn is consumed by `Event2StateHandler` etc. 

We'd keep the top level states ACCEPTED, PROVISIONING, READY but could also have more granular statuses for the Worker; e.g. ProcessorCreated, ManagedConnectorTopicCreated and ManagedConnectorCreated so that we would better know the complete state at any point in time.  

Each state handler can have different re-try schedules, different sub-statuses and re-try/time-out policies. 

DB transactions are isolated to each state transition. 

This would be closer to what @r00ta has prototyped and aligned with @lucamolteni work to date.

I'm probably the least experienced backend cloud developer here so share my opinion for discussion only.

**Pull request closed without merging**
