### PR TITLE
MGDOBR-630: Review the fields being logged

### PR DESCRIPTION
**Pull request by manstis**
[https://issues.redhat.com/browse/MGDOBR-630](https://issues.redhat.com/browse/MGDOBR-630)

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [x] Check if code and Github action workflows have been modified and if the modification is safe
- [x] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Comment by manstis** [comment]
@r00ta @kostola @danielezonca @lucamolteni It is simple enough to disable for `%dev`:

https://github.com/quarkiverse/quarkus-logging-json#configuration

If we agree, I'll add that to this PR.

**Review by r00ta — COMMENTED** [review]
Could you please add

```
%dev.quarkus.log.console.json=false
%test.quarkus.log.console.json=false
```

in order to switch back to standard logging for local development? 

In addition to that, we might move the logging settings to each specific application (and do not set them in the `infra` module). 

Thanks

**Review by robpblake — CHANGES_REQUESTED** [review]
@manstis Could you add the configuration to disable this in local-dev as per @r00ta comment.

cheers,

Rob

**Comment by manstis** [comment]
The `operator` is still showing JSON logging locally.. weird. I am putting it down to a caching issue somewhere.

I will try it again tomorrow as I can't see anything in the setup that would suggest the `operator` should be logging JSON.

**Comment by r00ta** [comment]
> The `operator` is still showing JSON logging locally.. weird. I am putting it down to a caching issue somewhere.
> 
> I will try it again tomorrow as I can't see anything in the setup that would suggest the `operator` should be logging JSON.

Are you using `shard-run.sh` to run the shard?

**Review by robpblake — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]

**Comment by manstis** [comment]
> Are you using `shard-run.sh` to run the shard?

Yes.

**Comment by manstis** [comment]
@r00ta I discovered that the `operator`, `ingress` and `executor` all ignore the `%dev` profile settings in `application.properties` and log as JSON regardless if the `io.quarkiverse.loggingjson:quarkus-logging-json` dependency is present **OR** I set `quarkus.log.console.json=false` i.e. without the profile prefix.

I am having a think...

**Comment by r00ta** [comment]
> @r00ta I discovered that the `operator`, `ingress` and `executor` all ignore the `%dev` profile settings in `application.properties` and log as JSON regardless if the `io.quarkiverse.loggingjson:quarkus-logging-json` dependency is present **OR** I set `quarkus.log.console.json=false` i.e. without the profile prefix.
> 
> I am having a think...

It's because the operator is run with the `minikube` profile. The ingress and executor are run with the default profile. 

So for the operator you have to add `%minikube....` and for the ingress/executor I'd leave them as they are. If needed the developer can add it on the fly during the development

**Comment by manstis** [comment]
Thank-you for the explanation @r00ta however I was mid-way through testing the change I've pushed here that allows switching between plain-text/JSON logging in the `operator`, `ingress` and `executor`. I tested locally with and without JSON logging enabled and the the logs for the three affected components are as required.

@r00ta @robpblake @sutaakar Please re-review.

**Review by sutaakar — APPROVED** [review]

**Review by r00ta — APPROVED** [review]

**Review by robpblake — APPROVED** [review]

**Pull request merged**
