### PR TITLE
MGDOBR-638: Processor Status is showing as Provisioning upon updating the same as existing filter payload

### PR DESCRIPTION
**Pull request by manstis**
[https://issues.redhat.com/browse/MGDOBR-638](https://issues.redhat.com/browse/MGDOBR-638)

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

### CODE REVIEW

**Comment by Srihari1192** [comment]
@manstis This fix should be taken care for all the supported filters. Issue still persist for filters **ValuesIn**..Can you apply the changes for Filter **ValuesIn** aswell

**Comment by manstis** [comment]
> @manstis This fix should be taken care for all the supported filters. Issue still persist for filters **ValuesIn**..Can you apply the changes for Filter **ValuesIn** aswell

I completely agree. I thought I'd found all sub-classes of `Filter`.

**Review by lucamolteni — APPROVED** [review]

**Comment by manstis** [comment]
@Srihari1192 Good catch. I've updated accordingly. Thank-you.

**Review by Srihari1192 — APPROVED** [review]
@manstis LGTM..Thanks

**Comment by manstis** [comment]
Hi @sutaakar I assume the e2e's are still failing due to the Managed Connector token change? Do you know if there is a PR to update it for the integration tests?

**Comment by sutaakar** [comment]
@manstis The tests are broken due to the unaligned CRD:
```
"stackTrace":"java.lang.IllegalArgumentException: No ProcessorType with value \"null\"\n\tat com.redhat.service.smartevents.infra.models.processors.ProcessorType.fromValue(ProcessorType.java:26)\n\tat com.redhat.service.smartevents.shard.operator.resources.BridgeExecutor.toDTO(BridgeExecutor.java:72)\n\tat com.redhat.service.smartevents.shard.operator.BridgeExecutorServiceImpl.fetchOrCreateBridgeExecutorDeployment(BridgeExecutorServiceImpl.java:106)\n\tat 
```
It should be addressed by https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/689

**Comment by manstis** [comment]
@sutaakar Don't [these](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/blob/main/integration-tests/src/test/resources/features/action-slack.feature#L12-L21) need updating too? The {{Processor}} definitions used in the e2e tests lack `ProcessorType` that leads to the NPE in the log you linked?
```
2022-04-29T06:05:35.7720839Z {"timestamp":"2022-04-29T05:58:10.138Z","loggerName":"io.javaoperatorsdk.operator.processing.event.ReconciliationDispatcher","level":"ERROR","message":"Error during event processing ExecutionScope{ resource id: CustomResourceID{name='ob-eaa642f2-a611-4d65-bc96-796f7615eae8', namespace='ob-1608dc1f-4139-49c5-ae22-afe73ed807d7'}, version: 2038} failed.","threadName":"EventHandler-bridgeexecutorcontroller","mdc":{"resource.kind":"BridgeExecutor","resource.resourceVersion":"2038","resource.namespace":"ob-1608dc1f-4139-49c5-ae22-afe73ed807d7","resource.name":"ob-eaa642f2-a611-4d65-bc96-796f7615eae8","resource.generation":"1","resource.apiVersion":"com.redhat.service.bridge/v1alpha1","resource.uid":"6f744f75-94c0-4570-84da-9316d4771430"},"hostName":"event-bridge-shard-operator-5b87ff968-sfvmr","stackTrace":"java.lang.IllegalArgumentException: No ProcessorType with value \"null\"\n\tat com.redhat.service.smartevents.infra.models.processors.ProcessorType.fromValue(ProcessorType.java:26)\n\tat com.redhat.service.smartevents.shard.operator.resources.BridgeExecutor.toDTO(BridgeExecutor.java:72)\n\tat 
```
Specifically `No ProcessorType with value \"null\"`?

**Pull request merged**
