### PR TITLE
MGDOBR-185 Add Keycloak installation instructions into Shard operat…

### PR DESCRIPTION
**Pull request by sutaakar**
…or readme

Signed-off-by: Karel Suta <ksuta@redhat.com>

[MGDOBR-185](https://issues.redhat.com/browse/MGDOBR-185) 

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

### CODE REVIEW

**Review by fjtirado — APPROVED** [review]
Great work @sutaakar 
Thanks a lot for all your help in the keycloak setup

**Review by ricardozanini — APPROVED** [review]
Guys, I'm getting a little worried about all this infra necessary to run the operator locally. It will be a burden to configure, run, and test it locally. Can we think of a workaround? 🤔

**Comment by robpblake** [comment]
> Guys, I'm getting a little worried about all this infra necessary to run the operator locally. It will be a burden to configure, run, and test it locally. Can we think of a workaround? 🤔

@ricardozanini A couple of things that I can see that _might_ make life easier for us:

* Create kustomize overlays to capture the majority of this setup so we get into the situation where we have:
  * kustomize build overlays/local-dev | kubectl apply -f - //installs local-dev
  * kustomize build overlays/integration-tests | kubectl apply -f - //installs integration-tests
  * kustomize build overlays/prod | kubectl apply -f - //installs prod
* We're close to starting the onboarding process into sso.{stage}.redhat.com. We can then take a call to externalise the Keycloak dependency here so local-dev/integration tests have a dependency on sso.stage.redhat.com for example. Trade-off being that if sso.stage.redhat.com is down, we're kinda blocked..

Just some initial thoughts.

**Comment by ricardozanini** [comment]
+1000 to have kustomize layers to configure it locally. I'd say to maybe go even further and do a `make run-local`. Kick up Kind or Minikube, install the bare minimum, and have the environment ready for tests.

**Review by r00ta — APPROVED** [review]

**Comment by sutaakar** [comment]
Fine for me to have a dedicated kustomize overlay spinning up all what is needed. That can be done as a first step, then leveraged by `make run-local`.

**Pull request merged**
