### PR TITLE
MGDOBR-1262: Processor: API CRU[D] operation

### PR DESCRIPTION
**Pull request by manstis**
[https://issues.redhat.com/browse/MGDOBR-1262](https://issues.redhat.com/browse/MGDOBR-1262)

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-XXX] - $clear_explanation_of_what_you_did"
- [x] The layers in the `kustomize` folder have been updated accordingly.
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.
- <b>Deploy BOT</b>
  Comment with `/deploy <dev,stable> when the PR has been merged to deploy to a target environment.

</details>

### CODE REVIEW

**Review by r00ta — APPROVED** [review]

**Comment by ChughShilpa** [comment]
This new V2 DELETE API  gives me '500 Internal Server Error'

**Review by r00ta — APPROVED** [review]

**Comment by ChughShilpa** [comment]
> > Delete API cannot make distinction whether the particular 'bridgeID' belongs to v1 or v2. Its just gives the error reason as
> > ```
> > "Processor with id '' does not exist on bridge '' for customer '' ''
> > ```
> 
> The User invokes either a `v1` or `v2` URL so I don't think we need to include any more information in the message.
> 
> That said.. it should be including the Processor Id, Bridge Id and Customer Id!!

I agree with you we don't need to include any other information. Actually, i should have made my statement more descriptive earlier and sorry for that..
What i meant above is that when i tried deleting processor (on v2 DELETE API) by passing bridgeID of v1 then the response also states 
```
Processor with id '' does not exist on bridge '' for customer ''
```

Instead it should include message something like this
```
Bridge with id '' for customer '' does not exist
```

as this bridge doesn't exist on v2

**Comment by ChughShilpa** [comment]
> every Processor operation.

Created a jira for further discussion
[https://issues.redhat.com/browse/MGDOBR-1325](url)

**Comment by ChughShilpa** [comment]
> This new V2 DELETE API gives me '500 Internal Server Error'

This is working now

**Review by ChughShilpa — APPROVED** [review]

**Pull request merged**
