### PR TITLE
MGDOBR-634: Exceptions from Managed Kafka/Connectors are not logged

### PR DESCRIPTION
**Pull request by manstis**
[https://issues.redhat.com/browse/MGDOBR-634](https://issues.redhat.com/browse/MGDOBR-634)

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

### CODE REVIEW

**Comment by sutaakar** [comment]
(Based on Sonarcloud complain) Thinking whether it would have sense to either log the error as done now and don't propagate it or to skip logging in client and log complete error in AbstractWorker. WDYT?

**Comment by manstis** [comment]
> (Based on Sonarcloud complain) Thinking whether it would have sense to either log the error as done now and don't propagate it or to skip logging in client and log complete error in AbstractWorker. WDYT?

@sutaakar I have reworked the exception handling for `getConnector(String connectorExternalId)` on #679 so what is contained in this PR for that method is already obsolete! Regarding your comment specifically the MC API throws a `ApiException` if the HTTP response is anything other than 2xx. However 404 and 410 are "handled exceptions" as far as our code is concerned and hence, in those circumstances, we do not want to propagate `ApiException` to `AbstractWorker`. I wrap and re-throw as that is the pattern that existed in the class before I came to make a change.

**Comment by robpblake** [comment]
@manstis I agree that your changes in #679 are the better option that this one. I'd suggest we close this and focus on getting #679 merged.

cheers,

Rob

**Comment by manstis** [comment]
> ...I'd suggest we close this and focus on getting #679 merged.

@robpblake OK, I've moved the additional logging in this PR to #679 too.

**Pull request closed without merging**
