### PR TITLE
MGDOBR-388: Decouple hard codes steps from provisioning

### PR DESCRIPTION
**Pull request by manstis**
See [MGDOBR-388](https://issues.redhat.com/browse/MGDOBR-388) 

Please make sure that your PR meets the following requirements:

- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [x] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [x] All new functionality is tested
- [x] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

* <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

* <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

### CODE REVIEW

**Comment by manstis** [comment]
@lucamolteni @robpblake This PR moves the close coupling of `ConnectorWorker` from `ProcessorWorker`.

It introduces the concept of a "chain or work" that is configured for Processors to also handle Connections. The separate Workers then only know of the work for themselves. It is also a first step to allowing Workers to run in parallel since we could now (after this PR) have one Work item for Processor and a separate Work item for Connectors.

**Comment by robpblake** [comment]
@manstis I would like us to get the environment stable with what we have right now before we make any more changes to our resilient provisioning process.

cheers,
Rob

**Comment by manstis** [comment]
@robpblake Indeed. This PR was submitted before this weeks events unfolded.

This PR can wait for now.

**Comment by manstis** [comment]
@robpblake @lucamolteni Did you want this one still on hold?

Would it be better if we deferred this until the retrospective that has been called for?

I know @kostola has a different opinion on the direction of the separate `Processor`/`Connector` workers.

**Comment by robpblake** [comment]
> @robpblake @lucamolteni Did you want this one still on hold?
> 
> Would it be better if we deferred this until the retrospective that has been called for?
> 
> I know @kostola has a different opinion on the direction of the separate `Processor`/`Connector` workers.

@manstis @lucamolteni Yes I would like to defer this work as I do not think we need to do it now. As I have said before, I would prefer to go with "hardcoded" but reliable for Service Preview.

So from my perspective, let's defer it because:

1. What we have right now is becoming stable and works for Service Preview
2. We have no requirement to extend what we have. We can revisit the discussion when those requirements come
3. I personally feel this PR is making things less clear as to how it works. What we have at the minute is fairly simple and readable IMHO

Please feel free to close this PR and I'm also comfortable with the issue going into the backlog.

cheers,

Rob

**Comment by manstis** [comment]
Will no do (for now, if ever).

**Pull request closed without merging**
