### PR TITLE
MGDOBR-322: refactoring of actions related classes into smaller modules

### PR DESCRIPTION
**Pull request by kostola**
[MGDOBR-322](https://issues.redhat.com/browse/MGDOBR-322)

## PR owner checklist

Please make sure that your PR meets the following requirements:

- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config).  
  *Run `mvn clean verify -DskipTests` so that imports are correctly set.*
- [ ] Your commit messages are clear and reference the JIRA issue e.g: "[MGDOBR-1] - $clear_explanation_of_what_you_did"
- [ ] All new functionality is tested
- [ ] Pull Request title is properly formatted: `MGDOBR-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

## PR reviewer(s) checklist

- [ ] Check if code and Github action workflows have been modified and if the modification is safe
- [ ] If the modification is safe, add the `safe to test` label

<details>
<summary>
How to trigger pipelines and use the bots:
</summary>

- <b>Run the end to end pipeline</b>  
  Annotate the pull request with the label: `safe to test`. If you want to run the pipeline again, remove and add it again.

- <b>Rebase the pull request</b>  
  Comment with: `/rebase`.

</details>

### CODE REVIEW

**Review by r00ta — COMMENTED** [review]
First of all I'd like to say very good job putting this together. I'm sure you had a big headache :) 
But, I'm personally -1 with that. 

As you can see there is no gain in creating 3 submodules **for each action**, because in the manager you import every single action definition with 
```
    <dependency>
      <groupId>com.redhat.service.bridge</groupId>
      <artifactId>processor-actions-kafkatopic-manager</artifactId>
    </dependency>
    <dependency>
      <groupId>com.redhat.service.bridge</groupId>
      <artifactId>processor-actions-sendtobridge-manager</artifactId>
    </dependency>
    .... all the other actions
```
and the same in the executor!
```
    <dependency>
      <groupId>com.redhat.service.bridge</groupId>
      <artifactId>processor-actions-kafkatopic-executor</artifactId>
    </dependency>
    <dependency>
      <groupId>com.redhat.service.bridge</groupId>
      <artifactId>processor-actions-sendtobridge-executor</artifactId>
    </dependency>
    ... all the other actions
```

So, I'd rather create **one submodule** that contains all the actions definitions and **one submodule** that contains all the runtimes.

**Comment by manstis** [comment]
I concur @r00ta comment. There are 20 modules relating to Actions most of which contain less than five files. Do we really need this level of granularity? As it stands there is also split packages across modules (that I believe is a bad idea) and some strange inheritance (or unclear naming).. for example why do both `SlackActionValidator` and `SlackActionConnector` implement `SlackAction` when they are in the same module and package (perhaps `SlackActionAcceptor` would be a clearer name looking at its implementation).

**Comment by kostola** [comment]
@r00ta I put this together because in our discussion this structure was proposed, but after implementing it I can say that I am against this too, because it increases the complexity too much.
I think the separation between core and executor/manager is the best and I am working on a simpler refactoring that uses only these three modules.

**Comment by kostola** [comment]
Closing this because #590 was merged instead

**Pull request closed without merging**
